language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  # Older version for compatibility with older Gammu
  - pip install python-gammu==2.6
  - pip install -r requirements-test.txt
script: 
  - ./manage.py check
  - coverage run --source=. ./manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
addons:
  apt:
    packages:
    - libgammu-dev
cache:
  pip: true
